Kirkbrae Property/Controllers/EnquiryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kirkbrae_Property.Models;

namespace Kirkbrae_Property.Controllers
{
    public partial class EnquiryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            //var enquiries = db.Enquiries.ToList();
            //if (enquiries == null)
            //{
                var enquiriesList = new List<Enquiry>();
                var enquiry = new Enquiry()
                {
                    Id = 1,
                    UserId = 1,
                    Message = "Is this property still available?",
                    Status = "Pending review",
                    LastUpdated = DateTime.Now
                };
                enquiriesList.Add(enquiry);
                return View(enquiriesList);
            //}
            //return View(db.Enquiries.ToList());
        }

        public ActionResult Details(int id = 0)
        {
            Enquiry enquiry = db.Enquiries.Find(id);
            if (enquiry == null)
            {
                return HttpNotFound();
            }
            return View(enquiry);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                var newEnquiry = new Enquiry
                {
                    UserId = 1,
                    Message = enquiry.Message,
                    Status = "Awaiting response",
                    LastUpdated = DateTime.UtcNow
                };

                db.Enquiries.Add(newEnquiry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(enquiry);
        }

        public ActionResult Edit(int id = 0)
        {
            Enquiry enquiry = db.Enquiries.Find(id);
            if (enquiry == null)
            {
                return HttpNotFound();
            }
            return View(enquiry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enquiry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enquiry);
        }

        public ActionResult Delete(int id = 0)
        {
            Enquiry enquiry = db.Enquiries.Find(id);
            if (enquiry == null)
            {
                return HttpNotFound();
            }

            return View(enquiry);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Database.ExecuteSqlCommand("DELETE FROM Enquiries WHERE ID = {0}", id.ToString());
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kirkbrae Property/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kirkbrae_Property.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authorize()
        {
            return View();
        }
    }
}

Kirkbrae Property/Controllers/PropertyController.cs
using System;
﻿using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kirkbrae_Property.Models;

namespace Kirkbrae_Property.Controllers
{
    public partial class PropertyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            //var properties = db.Properties.ToList();
            //if (properties == null)
            //{
                var propertiesList = new List<Property>();
                var property = new Property()
                {
                    Name = "Applewood",
                    Location = "Fulmar Brae, Edinburgh, EH11",
                    Listed = DateTime.Now.Date,
                    Price = 1000
                };
                propertiesList.Add(property);
                var property2 = new Property()
                {
                    Name = "Cabin",
                    Location = "West Pilton Rise, Edinburgh, EH11",
                    Listed = DateTime.Now.Date,
                    Price = 1200
                };
                propertiesList.Add(property2);
                var property3 = new Property()
                {
                    Name = "Deluxe Mansion",
                    Location = "Simpson View, Edinburgh, EH11",
                    Listed = DateTime.Now.Date,
                    Price = 1300
                };
                propertiesList.Add(property3);
                return View(propertiesList);
            //}
            //return View(db.Properties.ToList());
        }

        public ActionResult Details(int id = 0)
        {
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        public ActionResult Create()
        {
            return View();
        }

       [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult Create(Property property)
        {
            if (ModelState.IsValid)
            {
                db.Properties.Add(property);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(property);
        }

        public ActionResult Edit(int id = 0)
        {
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Property property)
        {
            if (ModelState.IsValid)
            {
                db.Entry(property).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(property);
        }

        public ActionResult Delete(int id = 0)
        {
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }

            return View(property);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Database.ExecuteSqlCommand("DELETE FROM Properties WHERE ID = {0}", id.ToString());
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kirkbrae Property/Controllers/UserController.cs
using System;
﻿using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kirkbrae_Property.Models;

namespace Kirkbrae_Property.Controllers
{
    public partial class UserController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //Registration Action
        [HttpGet]
        public ActionResult Registration(int id = 0)
        {
            User userModel = new User();
            return View(userModel);
        }

        //Registration POST Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration(User userModel)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                db.Users.Add(userModel);
                db.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration successful";
            return View("Registration", new User());
        }

        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        public ActionResult Details(int id = 0)
        {
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult Edit(int id = 0)
        {
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Delete(int id = 0)
        {
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Database.ExecuteSqlCommand("DELETE FROM Users WHERE ID = {0}", id.ToString());
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kirkbrae Property/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kirkbrae Property - @ViewBag.Title</title>
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.aspnetmvc.min.js"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
</head>
<body class="k-content">
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
        @Html.ActionLink("Kirkbrae Property", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample06">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Properties", "Index", "Property", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Enquiries", "Index", "Enquiry", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Sign In", "Index", "Login", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Register", "Registration", "User", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>

    <main>
        <div>
            @RenderBody()
        </div>
    </main>

    <footer class="footer text-center d-flex align-items-center">
        <div class="container-fluid">
            <p class="text-muted">Built by Kerry Robson | Copyright © @DateTime.Now.Year.</p>
        </div>
    </footer>
    @RenderSection("Scripts", false);
</body>
</html>